version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Data Source=/data/flytospace.db
      # Add Redis connection string env variable if you use one, e.g.:
      # - Redis__Connection=redis:6379
    volumes:
      - /var/lib/flytospace:/data
    ports:
      - "5050:8080"
    container_name: flytospace-api
    restart: always
    depends_on:
      - redis

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    container_name: flytospace-client
    restart: always

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
